sudo: required
services:
  - docker

before_install:
  - docker pull gcr.io/cpp-projects/cpp-ci:1

script:
  - >
    docker run -v `pwd`:/facter gcr.io/cpp-projects/cpp-ci:1 /bin/bash -c "
    cd /facter &&
    case $TARGET in
    doxygen)
      # Build docs
      cd lib
      doxygen 2>&1 | ( ! grep . )
      ruby docs/generate.rb > /tmp/facts.md
      ;;
    commits)
      shopt -s nocasematch
      git log --no-merges --pretty=%s master..$HEAD | while read line ; do
        if [[ ! $line =~ ^\((maint|doc|docs|packaging|fact-[0-9]+)\)|revert ]]; then
          echo -e \
            '\n\n\n\tThis commit summary did not match CONTRIBUTING.md guidelines:\n' \
            '\n\t\t$line\n' \
            '\tThe commit summary (i.e. the first line of the commit message) should start with one of:\n' \
            '\t\t(FACT-<digits>) # this is most common and should be a ticket at tickets.puppetlabs.com\n' \
            '\t\t(doc)\n' \
            '\t\t(docs)\n' \
            '\t\t(maint)\n' \
            '\t\t(packaging)\n' \
            '\n\tThis test for the commit summary is case-insensitive.\n\n\n'
          exit 1
        fi
      done
      ;;
    *)
      wget https://github.com/puppetlabs/leatherman/releases/download/${LEATHERMAN_VERSION}/leatherman.tar.gz
      tar xzvf leatherman.tar.gz --strip 1 -C /
      wget https://github.com/puppetlabs/cpp-hocon/releases/download/${CPPHOCON_VERSION}/cpp-hocon.tar.gz
      tar xzvf cpp-hocon.tar.gz --strip 1 -C /
      cmake $EXTRA_VARS .
      make $TARGET VERBOSE=1 -j2
      { [[ '$COVERALLS' != 'ON' ]] || coveralls --gcov-options '\-lp' -r . -b . -e src -e vendor >/dev/null || true; }
      ;;
    esac
    "

env:
  global:
    - LEATHERMAN_VERSION=1.4.0
    - CPPHOCON_VERSION=0.2.0
  matrix:
    - TARGET=cpplint
    - TARGET=cppcheck
    - TARGET=doxygen
    - TARGET=commits
    - TARGET="all test install ARGS=-V" EXTRA_VARS="-DBOOST_STATIC=ON"
    - TARGET="all test install ARGS=-V" EXTRA_VARS="-DBOOST_STATIC=ON -DCMAKE_BUILD_TYPE=Debug -DCOVERALLS=ON" COVERALLS=ON
